#!/usr/bin/env bash

export PID_FILE_PATH="/tmp/openApi.pid"
export LOG_FILE_PATH="/tmp/openApi.log"
export LOG_ERROR_FILE_PATH="/tmp/openApi.error.log"

. ./services.sh

run-script() {
  local action="$1" # Action
  openApi
}

before-start() {
  local action="$1" # Action

  echo "* Starting with $action"
}

after-finish() {
  local action="$1" # Action
  local serviceExitCode=$2 # Service exit code

  echo "* Finish with $action. Exit code: $serviceExitCode"
}

action="$1"
serviceName="openApi"
workDir="/opt/prod"

serviceMenu "$action" "$serviceName" run-script "$workDir" before-start after-finish
